# Generated by Django 2.2.5 on 2019-09-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Market.Category'),
            preserve_default=False,
        ),
    ]
