# Generated by Django 2.2.5 on 2019-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_products_categ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=20, verbose_name='имя'),
        ),
    ]
