# Generated by Django 2.2.5 on 2019-09-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20190917_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='колич.'),
        ),
        migrations.AddField(
            model_name='products',
            name='outdate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Праср.(Шт)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Market.Category', verbose_name='категория'),
        ),
    ]
