# Generated by Django 2.2.5 on 2019-09-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_auto_20190918_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='eng_name',
            field=models.CharField(db_index=True, default=2, max_length=20, verbose_name='name'),
            preserve_default=False,
        ),
    ]
